import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

function About() {
  return (
    <div className={styles.container}>
      <Head>
        <meta charSet="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
        />
        <meta name="description" content="Description" />
        <meta name="keywords" content="Keywords" />
        <title>Revenite About</title>

        <link rel="manifest" href="/manifest.json" />

        <meta name="theme-color" content="#317EFB" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Link href="/">
          <a>Home</a>
        </Link>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>About us...</h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export default About;
